"""
Caldwell Catalog Data
Source: http://astropixels.com/caldwell/caldwellcat.html

Complete list of all 109 Caldwell objects with NGC/IC cross-references,
coordinates (J2000), magnitudes, sizes, and constellations.
"""

CALDWELL_CATALOG = [
    # C1-C10
    {
        "caldwell": 1,
        "ngc": "NGC 188",
        "common_name": None,
        "type": "open_cluster",
        "ra_hours": 0.74,
        "dec_degrees": 85.33,
        "magnitude": 8.1,
        "size_arcmin": 14.0,
        "constellation": "Cep",
    },
    {
        "caldwell": 2,
        "ngc": "NGC 40",
        "common_name": "Bow Tie Nebula",
        "type": "planetary_nebula",
        "ra_hours": 0.22,
        "dec_degrees": 72.53,
        "magnitude": 11.6,
        "size_arcmin": 0.6,
        "constellation": "Cep",
    },
    {
        "caldwell": 3,
        "ngc": "NGC 4236",
        "common_name": None,
        "type": "galaxy",
        "ra_hours": 12.28,
        "dec_degrees": 69.47,
        "magnitude": 9.7,
        "size_arcmin": 21.0,
        "constellation": "Dra",
    },
    {
        "caldwell": 4,
        "ngc": "NGC 7023",
        "common_name": "Iris Nebula",
        "type": "nebula",
        "ra_hours": 21.02,
        "dec_degrees": 68.17,
        "magnitude": 6.8,
        "size_arcmin": 18.0,
        "constellation": "Cep",
    },
    {
        "caldwell": 5,
        "ngc": "IC 342",
        "common_name": None,
        "type": "galaxy",
        "ra_hours": 3.47,
        "dec_degrees": 68.10,
        "magnitude": 9.2,
        "size_arcmin": 21.0,
        "constellation": "Cam",
    },
    {
        "caldwell": 6,
        "ngc": "NGC 6543",
        "common_name": "Cat's Eye Nebula",
        "type": "planetary_nebula",
        "ra_hours": 17.98,
        "dec_degrees": 66.63,
        "magnitude": 8.8,
        "size_arcmin": 0.3,
        "constellation": "Dra",
    },
    {
        "caldwell": 7,
        "ngc": "NGC 2403",
        "common_name": None,
        "type": "galaxy",
        "ra_hours": 7.62,
        "dec_degrees": 65.60,
        "magnitude": 8.9,
        "size_arcmin": 22.0,
        "constellation": "Cam",
    },
    {
        "caldwell": 8,
        "ngc": "NGC 559",
        "common_name": None,
        "type": "open_cluster",
        "ra_hours": 1.49,
        "dec_degrees": 63.30,
        "magnitude": 9.5,
        "size_arcmin": 4.0,
        "constellation": "Cas",
    },
    {
        "caldwell": 9,
        "ngc": "IC 1396",
        "common_name": "Cave Nebula",
        "type": "nebula",
        "ra_hours": 21.63,
        "dec_degrees": 57.50,
        "magnitude": 3.5,
        "size_arcmin": 170.0,
        "constellation": "Cep",
    },
    {
        "caldwell": 10,
        "ngc": "NGC 663",
        "common_name": None,
        "type": "open_cluster",
        "ra_hours": 1.77,
        "dec_degrees": 61.25,
        "magnitude": 7.1,
        "size_arcmin": 16.0,
        "constellation": "Cas",
    },
    # C11-C20
    {
        "caldwell": 11,
        "ngc": "NGC 7635",
        "common_name": "Bubble Nebula",
        "type": "nebula",
        "ra_hours": 23.35,
        "dec_degrees": 61.20,
        "magnitude": 11.0,
        "size_arcmin": 15.0,
        "constellation": "Cas",
    },
    {
        "caldwell": 12,
        "ngc": "NGC 6946",
        "common_name": "Fireworks Galaxy",
        "type": "galaxy",
        "ra_hours": 20.58,
        "dec_degrees": 60.15,
        "magnitude": 9.6,
        "size_arcmin": 11.0,
        "constellation": "Cep",
    },
    {
        "caldwell": 13,
        "ngc": "NGC 457",
        "common_name": "Owl Cluster",
        "type": "open_cluster",
        "ra_hours": 1.32,
        "dec_degrees": 58.33,
        "magnitude": 6.4,
        "size_arcmin": 13.0,
        "constellation": "Cas",
    },
    {
        "caldwell": 14,
        "ngc": "NGC 869/884",
        "common_name": "Double Cluster",
        "type": "open_cluster",
        "ra_hours": 2.33,
        "dec_degrees": 57.13,
        "magnitude": 4.3,
        "size_arcmin": 30.0,
        "constellation": "Per",
    },
    {
        "caldwell": 15,
        "ngc": "NGC 6826",
        "common_name": "Blinking Planetary",
        "type": "planetary_nebula",
        "ra_hours": 19.75,
        "dec_degrees": 50.53,
        "magnitude": 8.8,
        "size_arcmin": 0.5,
        "constellation": "Cyg",
    },
    {
        "caldwell": 16,
        "ngc": "NGC 7243",
        "common_name": None,
        "type": "open_cluster",
        "ra_hours": 22.25,
        "dec_degrees": 49.88,
        "magnitude": 6.4,
        "size_arcmin": 21.0,
        "constellation": "Lac",
    },
    {
        "caldwell": 17,
        "ngc": "NGC 147",
        "common_name": None,
        "type": "galaxy",
        "ra_hours": 0.55,
        "dec_degrees": 48.50,
        "magnitude": 9.3,
        "size_arcmin": 13.0,
        "constellation": "Cas",
    },
    {
        "caldwell": 18,
        "ngc": "NGC 185",
        "common_name": None,
        "type": "galaxy",
        "ra_hours": 0.65,
        "dec_degrees": 48.33,
        "magnitude": 9.2,
        "size_arcmin": 12.0,
        "constellation": "Cas",
    },
    {
        "caldwell": 19,
        "ngc": "IC 5146",
        "common_name": "Cocoon Nebula",
        "type": "nebula",
        "ra_hours": 21.88,
        "dec_degrees": 47.27,
        "magnitude": 10.0,
        "size_arcmin": 12.0,
        "constellation": "Cyg",
    },
    {
        "caldwell": 20,
        "ngc": "NGC 7000",
        "common_name": "North America Nebula",
        "type": "nebula",
        "ra_hours": 20.98,
        "dec_degrees": 44.53,
        "magnitude": 4.0,
        "size_arcmin": 120.0,
        "constellation": "Cyg",
    },
    # C21-C30
    {
        "caldwell": 21,
        "ngc": "NGC 4449",
        "common_name": None,
        "type": "galaxy",
        "ra_hours": 12.47,
        "dec_degrees": 44.10,
        "magnitude": 9.6,
        "size_arcmin": 6.0,
        "constellation": "CVn",
    },
    {
        "caldwell": 22,
        "ngc": "NGC 7662",
        "common_name": "Blue Snowball",
        "type": "planetary_nebula",
        "ra_hours": 23.43,
        "dec_degrees": 42.55,
        "magnitude": 8.3,
        "size_arcmin": 0.3,
        "constellation": "And",
    },
    {
        "caldwell": 23,
        "ngc": "NGC 891",
        "common_name": None,
        "type": "galaxy",
        "ra_hours": 2.38,
        "dec_degrees": 42.35,
        "magnitude": 10.0,
        "size_arcmin": 14.0,
        "constellation": "And",
    },
    {
        "caldwell": 24,
        "ngc": "NGC 1275",
        "common_name": "Perseus A",
        "type": "galaxy",
        "ra_hours": 3.33,
        "dec_degrees": 41.52,
        "magnitude": 11.6,
        "size_arcmin": 2.6,
        "constellation": "Per",
    },
    {
        "caldwell": 25,
        "ngc": "NGC 2419",
        "common_name": "Intergalactic Wanderer",
        "type": "globular_cluster",
        "ra_hours": 7.63,
        "dec_degrees": 38.88,
        "magnitude": 10.4,
        "size_arcmin": 4.1,
        "constellation": "Lyn",
    },
    {
        "caldwell": 26,
        "ngc": "NGC 4244",
        "common_name": None,
        "type": "galaxy",
        "ra_hours": 12.29,
        "dec_degrees": 37.82,
        "magnitude": 10.2,
        "size_arcmin": 16.0,
        "constellation": "CVn",
    },
    {
        "caldwell": 27,
        "ngc": "NGC 6888",
        "common_name": "Crescent Nebula",
        "type": "nebula",
        "ra_hours": 20.20,
        "dec_degrees": 38.35,
        "magnitude": 7.4,
        "size_arcmin": 20.0,
        "constellation": "Cyg",
    },
    {
        "caldwell": 28,
        "ngc": "NGC 752",
        "common_name": None,
        "type": "open_cluster",
        "ra_hours": 1.95,
        "dec_degrees": 37.67,
        "magnitude": 5.7,
        "size_arcmin": 50.0,
        "constellation": "And",
    },
    {
        "caldwell": 29,
        "ngc": "NGC 5005",
        "common_name": None,
        "type": "galaxy",
        "ra_hours": 13.18,
        "dec_degrees": 37.05,
        "magnitude": 9.8,
        "size_arcmin": 5.4,
        "constellation": "CVn",
    },
    {
        "caldwell": 30,
        "ngc": "NGC 7331",
        "common_name": None,
        "type": "galaxy",
        "ra_hours": 22.62,
        "dec_degrees": 34.42,
        "magnitude": 9.5,
        "size_arcmin": 11.0,
        "constellation": "Peg",
    },
    # C31-C40
    {
        "caldwell": 31,
        "ngc": "IC 405",
        "common_name": "Flaming Star Nebula",
        "type": "nebula",
        "ra_hours": 5.27,
        "dec_degrees": 34.27,
        "magnitude": 6.0,
        "size_arcmin": 30.0,
        "constellation": "Aur",
    },
    {
        "caldwell": 32,
        "ngc": "NGC 4631",
        "common_name": "Whale Galaxy",
        "type": "galaxy",
        "ra_hours": 12.70,
        "dec_degrees": 32.53,
        "magnitude": 9.2,
        "size_arcmin": 15.0,
        "constellation": "CVn",
    },
    {
        "caldwell": 33,
        "ngc": "NGC 6992/5",
        "common_name": "Eastern Veil Nebula",
        "type": "nebula",
        "ra_hours": 20.95,
        "dec_degrees": 31.72,
        "magnitude": 7.0,
        "size_arcmin": 60.0,
        "constellation": "Cyg",
    },
    {
        "caldwell": 34,
        "ngc": "NGC 6960",
        "common_name": "Western Veil Nebula",
        "type": "nebula",
        "ra_hours": 20.75,
        "dec_degrees": 30.72,
        "magnitude": 7.0,
        "size_arcmin": 70.0,
        "constellation": "Cyg",
    },
    {
        "caldwell": 35,
        "ngc": "NGC 4889",
        "common_name": None,
        "type": "galaxy",
        "ra_hours": 13.00,
        "dec_degrees": 27.98,
        "magnitude": 11.4,
        "size_arcmin": 3.0,
        "constellation": "Com",
    },
    {
        "caldwell": 36,
        "ngc": "NGC 4559",
        "common_name": None,
        "type": "galaxy",
        "ra_hours": 12.60,
        "dec_degrees": 27.97,
        "magnitude": 10.0,
        "size_arcmin": 10.0,
        "constellation": "Com",
    },
    {
        "caldwell": 37,
        "ngc": "NGC 6885",
        "common_name": None,
        "type": "open_cluster",
        "ra_hours": 20.20,
        "dec_degrees": 26.48,
        "magnitude": 5.7,
        "size_arcmin": 7.0,
        "constellation": "Vul",
    },
    {
        "caldwell": 38,
        "ngc": "NGC 4565",
        "common_name": "Needle Galaxy",
        "type": "galaxy",
        "ra_hours": 12.60,
        "dec_degrees": 25.98,
        "magnitude": 9.6,
        "size_arcmin": 16.0,
        "constellation": "Com",
    },
    {
        "caldwell": 39,
        "ngc": "NGC 2392",
        "common_name": "Eskimo Nebula",
        "type": "planetary_nebula",
        "ra_hours": 7.48,
        "dec_degrees": 20.92,
        "magnitude": 9.2,
        "size_arcmin": 0.7,
        "constellation": "Gem",
    },
    {
        "caldwell": 40,
        "ngc": "NGC 3626",
        "common_name": None,
        "type": "galaxy",
        "ra_hours": 11.33,
        "dec_degrees": 18.35,
        "magnitude": 10.9,
        "size_arcmin": 3.0,
        "constellation": "Leo",
    },
    # C41-C50
    {
        "caldwell": 41,
        "ngc": "NGC 4238",
        "common_name": "Hyades",
        "type": "open_cluster",
        "ra_hours": 4.45,
        "dec_degrees": 15.87,
        "magnitude": 0.5,
        "size_arcmin": 330.0,
        "constellation": "Tau",
    },
    {
        "caldwell": 42,
        "ngc": "NGC 7006",
        "common_name": None,
        "type": "globular_cluster",
        "ra_hours": 21.02,
        "dec_degrees": 16.18,
        "magnitude": 10.6,
        "size_arcmin": 3.6,
        "constellation": "Del",
    },
    {
        "caldwell": 43,
        "ngc": "NGC 7814",
        "common_name": None,
        "type": "galaxy",
        "ra_hours": 0.05,
        "dec_degrees": 16.15,
        "magnitude": 10.5,
        "size_arcmin": 6.0,
        "constellation": "Peg",
    },
    {
        "caldwell": 44,
        "ngc": "NGC 7479",
        "common_name": None,
        "type": "galaxy",
        "ra_hours": 23.08,
        "dec_degrees": 12.32,
        "magnitude": 11.0,
        "size_arcmin": 4.0,
        "constellation": "Peg",
    },
    {
        "caldwell": 45,
        "ngc": "NGC 5248",
        "common_name": None,
        "type": "galaxy",
        "ra_hours": 13.62,
        "dec_degrees": 8.88,
        "magnitude": 10.2,
        "size_arcmin": 6.0,
        "constellation": "Boo",
    },
    {
        "caldwell": 46,
        "ngc": "NGC 2261",
        "common_name": "Hubble's Variable Nebula",
        "type": "nebula",
        "ra_hours": 6.65,
        "dec_degrees": 8.73,
        "magnitude": 10.0,
        "size_arcmin": 2.0,
        "constellation": "Mon",
    },
    {
        "caldwell": 47,
        "ngc": "NGC 6934",
        "common_name": None,
        "type": "globular_cluster",
        "ra_hours": 20.57,
        "dec_degrees": 7.40,
        "magnitude": 8.9,
        "size_arcmin": 7.1,
        "constellation": "Del",
    },
    {
        "caldwell": 48,
        "ngc": "NGC 2775",
        "common_name": None,
        "type": "galaxy",
        "ra_hours": 9.17,
        "dec_degrees": 7.03,
        "magnitude": 10.3,
        "size_arcmin": 4.5,
        "constellation": "Cnc",
    },
    {
        "caldwell": 49,
        "ngc": "NGC 2237-9",
        "common_name": "Rosette Nebula",
        "type": "nebula",
        "ra_hours": 6.53,
        "dec_degrees": 5.03,
        "magnitude": 6.0,
        "size_arcmin": 80.0,
        "constellation": "Mon",
    },
    {
        "caldwell": 50,
        "ngc": "NGC 2244",
        "common_name": "Satellite of Rosette",
        "type": "open_cluster",
        "ra_hours": 6.53,
        "dec_degrees": 4.90,
        "magnitude": 4.8,
        "size_arcmin": 24.0,
        "constellation": "Mon",
    },
    # C51-C60
    {
        "caldwell": 51,
        "ngc": "IC 1613",
        "common_name": None,
        "type": "galaxy",
        "ra_hours": 1.08,
        "dec_degrees": 2.12,
        "magnitude": 9.3,
        "size_arcmin": 12.0,
        "constellation": "Cet",
    },
    {
        "caldwell": 52,
        "ngc": "NGC 4697",
        "common_name": None,
        "type": "galaxy",
        "ra_hours": 12.80,
        "dec_degrees": -5.80,
        "magnitude": 9.2,
        "size_arcmin": 6.0,
        "constellation": "Vir",
    },
    {
        "caldwell": 53,
        "ngc": "NGC 3115",
        "common_name": "Spindle Galaxy",
        "type": "galaxy",
        "ra_hours": 10.08,
        "dec_degrees": -7.72,
        "magnitude": 9.1,
        "size_arcmin": 8.0,
        "constellation": "Sex",
    },
    {
        "caldwell": 54,
        "ngc": "NGC 2506",
        "common_name": None,
        "type": "open_cluster",
        "ra_hours": 8.00,
        "dec_degrees": -10.78,
        "magnitude": 7.6,
        "size_arcmin": 7.0,
        "constellation": "Mon",
    },
    {
        "caldwell": 55,
        "ngc": "NGC 7009",
        "common_name": "Saturn Nebula",
        "type": "planetary_nebula",
        "ra_hours": 21.07,
        "dec_degrees": -11.37,
        "magnitude": 8.0,
        "size_arcmin": 0.4,
        "constellation": "Aqr",
    },
    {
        "caldwell": 56,
        "ngc": "NGC 246",
        "common_name": "Skull Nebula",
        "type": "planetary_nebula",
        "ra_hours": 0.78,
        "dec_degrees": -11.88,
        "magnitude": 8.0,
        "size_arcmin": 4.0,
        "constellation": "Cet",
    },
    {
        "caldwell": 57,
        "ngc": "NGC 6822",
        "common_name": "Barnard's Galaxy",
        "type": "galaxy",
        "ra_hours": 19.75,
        "dec_degrees": -14.80,
        "magnitude": 9.3,
        "size_arcmin": 15.0,
        "constellation": "Sgr",
    },
    {
        "caldwell": 58,
        "ngc": "NGC 2360",
        "common_name": None,
        "type": "open_cluster",
        "ra_hours": 7.30,
        "dec_degrees": -15.63,
        "magnitude": 7.2,
        "size_arcmin": 13.0,
        "constellation": "CMa",
    },
    {
        "caldwell": 59,
        "ngc": "NGC 3242",
        "common_name": "Ghost of Jupiter",
        "type": "planetary_nebula",
        "ra_hours": 10.42,
        "dec_degrees": -18.63,
        "magnitude": 8.6,
        "size_arcmin": 0.3,
        "constellation": "Hya",
    },
    {
        "caldwell": 60,
        "ngc": "NGC 4038",
        "common_name": "Antennae Galaxy",
        "type": "galaxy",
        "ra_hours": 12.03,
        "dec_degrees": -18.87,
        "magnitude": 10.9,
        "size_arcmin": 5.0,
        "constellation": "Crv",
    },
    # C61-C70
    {
        "caldwell": 61,
        "ngc": "NGC 4039",
        "common_name": "Antennae Galaxy",
        "type": "galaxy",
        "ra_hours": 12.03,
        "dec_degrees": -18.90,
        "magnitude": 13.0,
        "size_arcmin": 3.0,
        "constellation": "Crv",
    },
    {
        "caldwell": 62,
        "ngc": "NGC 247",
        "common_name": None,
        "type": "galaxy",
        "ra_hours": 0.78,
        "dec_degrees": -20.77,
        "magnitude": 9.1,
        "size_arcmin": 20.0,
        "constellation": "Cet",
    },
    {
        "caldwell": 63,
        "ngc": "NGC 7293",
        "common_name": "Helix Nebula",
        "type": "planetary_nebula",
        "ra_hours": 22.48,
        "dec_degrees": -20.83,
        "magnitude": 7.3,
        "size_arcmin": 13.0,
        "constellation": "Aqr",
    },
    {
        "caldwell": 64,
        "ngc": "NGC 2362",
        "common_name": "Tau Canis Majoris Cluster",
        "type": "open_cluster",
        "ra_hours": 7.30,
        "dec_degrees": -24.95,
        "magnitude": 4.1,
        "size_arcmin": 8.0,
        "constellation": "CMa",
    },
    {
        "caldwell": 65,
        "ngc": "NGC 253",
        "common_name": "Sculptor Galaxy",
        "type": "galaxy",
        "ra_hours": 0.78,
        "dec_degrees": -25.28,
        "magnitude": 7.6,
        "size_arcmin": 25.0,
        "constellation": "Scl",
    },
    {
        "caldwell": 66,
        "ngc": "NGC 5694",
        "common_name": None,
        "type": "globular_cluster",
        "ra_hours": 14.65,
        "dec_degrees": -26.53,
        "magnitude": 10.2,
        "size_arcmin": 3.6,
        "constellation": "Hya",
    },
    {
        "caldwell": 67,
        "ngc": "NGC 1097",
        "common_name": None,
        "type": "galaxy",
        "ra_hours": 2.77,
        "dec_degrees": -30.28,
        "magnitude": 9.5,
        "size_arcmin": 9.0,
        "constellation": "For",
    },
    {
        "caldwell": 68,
        "ngc": "NGC 6729",
        "common_name": None,
        "type": "nebula",
        "ra_hours": 19.03,
        "dec_degrees": -36.95,
        "magnitude": 9.7,
        "size_arcmin": 1.0,
        "constellation": "CrA",
    },
    {
        "caldwell": 69,
        "ngc": "NGC 6302",
        "common_name": "Bug Nebula",
        "type": "planetary_nebula",
        "ra_hours": 17.23,
        "dec_degrees": -37.10,
        "magnitude": 9.6,
        "size_arcmin": 0.8,
        "constellation": "Sco",
    },
    {
        "caldwell": 70,
        "ngc": "NGC 300",
        "common_name": None,
        "type": "galaxy",
        "ra_hours": 0.92,
        "dec_degrees": -37.68,
        "magnitude": 8.1,
        "size_arcmin": 20.0,
        "constellation": "Scl",
    },
    # C71-C80
    {
        "caldwell": 71,
        "ngc": "NGC 2477",
        "common_name": None,
        "type": "open_cluster",
        "ra_hours": 7.87,
        "dec_degrees": -38.55,
        "magnitude": 5.8,
        "size_arcmin": 27.0,
        "constellation": "Pup",
    },
    {
        "caldwell": 72,
        "ngc": "NGC 55",
        "common_name": None,
        "type": "galaxy",
        "ra_hours": 0.25,
        "dec_degrees": -39.20,
        "magnitude": 8.0,
        "size_arcmin": 32.0,
        "constellation": "Scl",
    },
    {
        "caldwell": 73,
        "ngc": "NGC 1851",
        "common_name": None,
        "type": "globular_cluster",
        "ra_hours": 5.23,
        "dec_degrees": -40.05,
        "magnitude": 7.3,
        "size_arcmin": 11.0,
        "constellation": "Col",
    },
    {
        "caldwell": 74,
        "ngc": "NGC 3132",
        "common_name": "Eight-Burst Nebula",
        "type": "planetary_nebula",
        "ra_hours": 10.12,
        "dec_degrees": -40.43,
        "magnitude": 8.2,
        "size_arcmin": 0.8,
        "constellation": "Vel",
    },
    {
        "caldwell": 75,
        "ngc": "NGC 6124",
        "common_name": None,
        "type": "open_cluster",
        "ra_hours": 16.43,
        "dec_degrees": -40.65,
        "magnitude": 5.8,
        "size_arcmin": 29.0,
        "constellation": "Sco",
    },
    {
        "caldwell": 76,
        "ngc": "NGC 6231",
        "common_name": None,
        "type": "open_cluster",
        "ra_hours": 16.90,
        "dec_degrees": -41.82,
        "magnitude": 2.6,
        "size_arcmin": 15.0,
        "constellation": "Sco",
    },
    {
        "caldwell": 77,
        "ngc": "NGC 5128",
        "common_name": "Centaurus A",
        "type": "galaxy",
        "ra_hours": 13.42,
        "dec_degrees": -43.02,
        "magnitude": 6.8,
        "size_arcmin": 18.0,
        "constellation": "Cen",
    },
    {
        "caldwell": 78,
        "ngc": "NGC 6541",
        "common_name": None,
        "type": "globular_cluster",
        "ra_hours": 18.13,
        "dec_degrees": -43.72,
        "magnitude": 6.6,
        "size_arcmin": 13.0,
        "constellation": "CrA",
    },
    {
        "caldwell": 79,
        "ngc": "NGC 3201",
        "common_name": None,
        "type": "globular_cluster",
        "ra_hours": 10.29,
        "dec_degrees": -46.40,
        "magnitude": 6.7,
        "size_arcmin": 18.0,
        "constellation": "Vel",
    },
    {
        "caldwell": 80,
        "ngc": "NGC 5139",
        "common_name": "Omega Centauri",
        "type": "globular_cluster",
        "ra_hours": 13.45,
        "dec_degrees": -47.48,
        "magnitude": 3.6,
        "size_arcmin": 36.0,
        "constellation": "Cen",
    },
    # C81-C90
    {
        "caldwell": 81,
        "ngc": "NGC 6352",
        "common_name": None,
        "type": "globular_cluster",
        "ra_hours": 17.43,
        "dec_degrees": -48.42,
        "magnitude": 8.1,
        "size_arcmin": 7.0,
        "constellation": "Ara",
    },
    {
        "caldwell": 82,
        "ngc": "NGC 6193",
        "common_name": None,
        "type": "open_cluster",
        "ra_hours": 16.68,
        "dec_degrees": -48.77,
        "magnitude": 5.2,
        "size_arcmin": 15.0,
        "constellation": "Ara",
    },
    {
        "caldwell": 83,
        "ngc": "NGC 4945",
        "common_name": None,
        "type": "galaxy",
        "ra_hours": 13.08,
        "dec_degrees": -49.47,
        "magnitude": 9.5,
        "size_arcmin": 20.0,
        "constellation": "Cen",
    },
    {
        "caldwell": 84,
        "ngc": "NGC 5286",
        "common_name": None,
        "type": "globular_cluster",
        "ra_hours": 13.77,
        "dec_degrees": -51.37,
        "magnitude": 7.6,
        "size_arcmin": 9.0,
        "constellation": "Cen",
    },
    {
        "caldwell": 85,
        "ngc": "IC 2391",
        "common_name": "Omicron Velorum Cluster",
        "type": "open_cluster",
        "ra_hours": 8.67,
        "dec_degrees": -53.05,
        "magnitude": 2.5,
        "size_arcmin": 50.0,
        "constellation": "Vel",
    },
    {
        "caldwell": 86,
        "ngc": "NGC 6397",
        "common_name": None,
        "type": "globular_cluster",
        "ra_hours": 17.68,
        "dec_degrees": -53.67,
        "magnitude": 5.3,
        "size_arcmin": 26.0,
        "constellation": "Ara",
    },
    {
        "caldwell": 87,
        "ngc": "NGC 1261",
        "common_name": None,
        "type": "globular_cluster",
        "ra_hours": 3.20,
        "dec_degrees": -55.22,
        "magnitude": 8.4,
        "size_arcmin": 7.0,
        "constellation": "Hor",
    },
    {
        "caldwell": 88,
        "ngc": "NGC 5823",
        "common_name": None,
        "type": "open_cluster",
        "ra_hours": 15.08,
        "dec_degrees": -55.60,
        "magnitude": 7.9,
        "size_arcmin": 10.0,
        "constellation": "Cir",
    },
    {
        "caldwell": 89,
        "ngc": "NGC 6087",
        "common_name": None,
        "type": "open_cluster",
        "ra_hours": 16.31,
        "dec_degrees": -57.93,
        "magnitude": 5.4,
        "size_arcmin": 12.0,
        "constellation": "Nor",
    },
    {
        "caldwell": 90,
        "ngc": "NGC 2867",
        "common_name": None,
        "type": "planetary_nebula",
        "ra_hours": 9.35,
        "dec_degrees": -58.32,
        "magnitude": 9.7,
        "size_arcmin": 0.2,
        "constellation": "Car",
    },
    # C91-C100
    {
        "caldwell": 91,
        "ngc": "NGC 3532",
        "common_name": "Wishing Well Cluster",
        "type": "open_cluster",
        "ra_hours": 11.10,
        "dec_degrees": -58.67,
        "magnitude": 3.0,
        "size_arcmin": 55.0,
        "constellation": "Car",
    },
    {
        "caldwell": 92,
        "ngc": "NGC 3372",
        "common_name": "Eta Carinae Nebula",
        "type": "nebula",
        "ra_hours": 10.75,
        "dec_degrees": -59.87,
        "magnitude": 3.0,
        "size_arcmin": 120.0,
        "constellation": "Car",
    },
    {
        "caldwell": 93,
        "ngc": "NGC 6752",
        "common_name": None,
        "type": "globular_cluster",
        "ra_hours": 19.18,
        "dec_degrees": -59.98,
        "magnitude": 5.4,
        "size_arcmin": 20.0,
        "constellation": "Pav",
    },
    {
        "caldwell": 94,
        "ngc": "NGC 4755",
        "common_name": "Jewel Box",
        "type": "open_cluster",
        "ra_hours": 12.88,
        "dec_degrees": -60.33,
        "magnitude": 4.2,
        "size_arcmin": 10.0,
        "constellation": "Cru",
    },
    {
        "caldwell": 95,
        "ngc": "NGC 6025",
        "common_name": None,
        "type": "open_cluster",
        "ra_hours": 16.05,
        "dec_degrees": -60.50,
        "magnitude": 5.1,
        "size_arcmin": 12.0,
        "constellation": "TrA",
    },
    {
        "caldwell": 96,
        "ngc": "NGC 2516",
        "common_name": None,
        "type": "open_cluster",
        "ra_hours": 7.97,
        "dec_degrees": -60.87,
        "magnitude": 3.8,
        "size_arcmin": 30.0,
        "constellation": "Car",
    },
    {
        "caldwell": 97,
        "ngc": "NGC 3766",
        "common_name": None,
        "type": "open_cluster",
        "ra_hours": 11.60,
        "dec_degrees": -61.60,
        "magnitude": 5.3,
        "size_arcmin": 12.0,
        "constellation": "Cen",
    },
    {
        "caldwell": 98,
        "ngc": "NGC 4609",
        "common_name": None,
        "type": "open_cluster",
        "ra_hours": 12.70,
        "dec_degrees": -62.97,
        "magnitude": 6.9,
        "size_arcmin": 5.0,
        "constellation": "Cru",
    },
    {
        "caldwell": 99,
        "ngc": "NGC 4052",
        "common_name": "Coal Sack",
        "type": "nebula",
        "ra_hours": 12.85,
        "dec_degrees": -63.00,
        "magnitude": None,
        "size_arcmin": 400.0,
        "constellation": "Cru",
    },
    {
        "caldwell": 100,
        "ngc": "IC 2944",
        "common_name": "Running Chicken Nebula",
        "type": "nebula",
        "ra_hours": 11.60,
        "dec_degrees": -63.03,
        "magnitude": 4.5,
        "size_arcmin": 75.0,
        "constellation": "Cen",
    },
    # C101-C109
    {
        "caldwell": 101,
        "ngc": "NGC 6744",
        "common_name": None,
        "type": "galaxy",
        "ra_hours": 19.15,
        "dec_degrees": -63.85,
        "magnitude": 8.3,
        "size_arcmin": 16.0,
        "constellation": "Pav",
    },
    {
        "caldwell": 102,
        "ngc": "IC 2602",
        "common_name": "Southern Pleiades",
        "type": "open_cluster",
        "ra_hours": 10.72,
        "dec_degrees": -64.40,
        "magnitude": 1.9,
        "size_arcmin": 50.0,
        "constellation": "Car",
    },
    {
        "caldwell": 103,
        "ngc": "NGC 2070",
        "common_name": "Tarantula Nebula",
        "type": "nebula",
        "ra_hours": 5.65,
        "dec_degrees": -69.10,
        "magnitude": 8.0,
        "size_arcmin": 40.0,
        "constellation": "Dor",
    },
    {
        "caldwell": 104,
        "ngc": "NGC 362",
        "common_name": None,
        "type": "globular_cluster",
        "ra_hours": 1.05,
        "dec_degrees": -70.85,
        "magnitude": 6.4,
        "size_arcmin": 13.0,
        "constellation": "Tuc",
    },
    {
        "caldwell": 105,
        "ngc": "NGC 4833",
        "common_name": None,
        "type": "globular_cluster",
        "ra_hours": 12.99,
        "dec_degrees": -70.88,
        "magnitude": 7.4,
        "size_arcmin": 14.0,
        "constellation": "Mus",
    },
    {
        "caldwell": 106,
        "ngc": "NGC 104",
        "common_name": "47 Tucanae",
        "type": "globular_cluster",
        "ra_hours": 0.40,
        "dec_degrees": -72.08,
        "magnitude": 4.0,
        "size_arcmin": 31.0,
        "constellation": "Tuc",
    },
    {
        "caldwell": 107,
        "ngc": "NGC 6101",
        "common_name": None,
        "type": "globular_cluster",
        "ra_hours": 16.43,
        "dec_degrees": -72.20,
        "magnitude": 9.3,
        "size_arcmin": 11.0,
        "constellation": "Aps",
    },
    {
        "caldwell": 108,
        "ngc": "NGC 4372",
        "common_name": None,
        "type": "globular_cluster",
        "ra_hours": 12.43,
        "dec_degrees": -72.67,
        "magnitude": 7.2,
        "size_arcmin": 19.0,
        "constellation": "Mus",
    },
    {
        "caldwell": 109,
        "ngc": "NGC 3195",
        "common_name": None,
        "type": "planetary_nebula",
        "ra_hours": 10.15,
        "dec_degrees": -80.85,
        "magnitude": 11.6,
        "size_arcmin": 0.6,
        "constellation": "Cha",
    },
]
