"""initial_schema

Revision ID: 00000001_init
Revises:
Create Date: 2026-02-12 19:29:40.578298

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00000001_init"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("value_type", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("is_secret", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_app_settings_category"), "app_settings", ["category"], unique=False)
    op.create_index(op.f("ix_app_settings_id"), "app_settings", ["id"], unique=False)
    op.create_index(op.f("ix_app_settings_key"), "app_settings", ["key"], unique=True)
    op.create_table(
        "asteroid_catalog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("designation", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("discovery_date", sa.Date(), nullable=True),
        sa.Column("epoch_jd", sa.Float(), nullable=False),
        sa.Column("perihelion_distance_au", sa.Float(), nullable=False),
        sa.Column("eccentricity", sa.Float(), nullable=False),
        sa.Column("inclination_deg", sa.Float(), nullable=False),
        sa.Column("arg_perihelion_deg", sa.Float(), nullable=False),
        sa.Column("ascending_node_deg", sa.Float(), nullable=False),
        sa.Column("mean_anomaly_deg", sa.Float(), nullable=False),
        sa.Column("semi_major_axis_au", sa.Float(), nullable=False),
        sa.Column("absolute_magnitude", sa.Float(), nullable=True),
        sa.Column("slope_parameter", sa.Float(), nullable=True),
        sa.Column("current_magnitude", sa.Float(), nullable=True),
        sa.Column("diameter_km", sa.Float(), nullable=True),
        sa.Column("albedo", sa.Float(), nullable=True),
        sa.Column("spectral_type", sa.String(length=10), nullable=True),
        sa.Column("rotation_period_hours", sa.Float(), nullable=True),
        sa.Column("asteroid_type", sa.String(length=20), nullable=True),
        sa.Column("data_source", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("designation"),
    )
    op.create_index(op.f("ix_asteroid_catalog_id"), "asteroid_catalog", ["id"], unique=False)
    op.create_table(
        "capture_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("catalog_id", sa.String(length=50), nullable=False),
        sa.Column("total_exposure_seconds", sa.Integer(), nullable=True),
        sa.Column("total_frames", sa.Integer(), nullable=True),
        sa.Column("total_sessions", sa.Integer(), nullable=True),
        sa.Column("first_captured_at", sa.DateTime(), nullable=True),
        sa.Column("last_captured_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("suggested_status", sa.String(length=20), nullable=True),
        sa.Column("best_fwhm", sa.Float(), nullable=True),
        sa.Column("best_star_count", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_capture_history_catalog_id"), "capture_history", ["catalog_id"], unique=True)
    op.create_table(
        "comet_catalog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("designation", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("discovery_date", sa.Date(), nullable=True),
        sa.Column("epoch_jd", sa.Float(), nullable=False),
        sa.Column("perihelion_distance_au", sa.Float(), nullable=False),
        sa.Column("eccentricity", sa.Float(), nullable=False),
        sa.Column("inclination_deg", sa.Float(), nullable=False),
        sa.Column("arg_perihelion_deg", sa.Float(), nullable=False),
        sa.Column("ascending_node_deg", sa.Float(), nullable=False),
        sa.Column("perihelion_time_jd", sa.Float(), nullable=False),
        sa.Column("absolute_magnitude", sa.Float(), nullable=False),
        sa.Column("magnitude_slope", sa.Float(), nullable=False),
        sa.Column("current_magnitude", sa.Float(), nullable=True),
        sa.Column("activity_status", sa.String(length=20), nullable=True),
        sa.Column("comet_type", sa.String(length=20), nullable=True),
        sa.Column("data_source", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("designation"),
    )
    op.create_index(op.f("ix_comet_catalog_id"), "comet_catalog", ["id"], unique=False)
    op.create_table(
        "constellation_names",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("abbreviation", sa.String(length=3), nullable=False),
        sa.Column("full_name", sa.String(length=50), nullable=False),
        sa.Column("common_name", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("abbreviation"),
    )
    op.create_index(op.f("ix_constellation_names_id"), "constellation_names", ["id"], unique=False)
    op.create_table(
        "dso_catalog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("catalog_name", sa.String(length=10), nullable=False),
        sa.Column("catalog_number", sa.Integer(), nullable=False),
        sa.Column("common_name", sa.String(length=100), nullable=True),
        sa.Column("caldwell_number", sa.Integer(), nullable=True),
        sa.Column("ra_hours", sa.Float(), nullable=False),
        sa.Column("dec_degrees", sa.Float(), nullable=False),
        sa.Column("object_type", sa.String(length=50), nullable=False),
        sa.Column("magnitude", sa.Float(), nullable=True),
        sa.Column("surface_brightness", sa.Float(), nullable=True),
        sa.Column("size_major_arcmin", sa.Float(), nullable=True),
        sa.Column("size_minor_arcmin", sa.Float(), nullable=True),
        sa.Column("constellation", sa.String(length=3), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dso_catalog_catalog_name"), "dso_catalog", ["catalog_name"], unique=False)
    op.create_index(op.f("ix_dso_catalog_catalog_number"), "dso_catalog", ["catalog_number"], unique=False)
    op.create_index(op.f("ix_dso_catalog_common_name"), "dso_catalog", ["common_name"], unique=False)
    op.create_index(op.f("ix_dso_catalog_constellation"), "dso_catalog", ["constellation"], unique=False)
    op.create_index(op.f("ix_dso_catalog_dec_degrees"), "dso_catalog", ["dec_degrees"], unique=False)
    op.create_index(op.f("ix_dso_catalog_id"), "dso_catalog", ["id"], unique=False)
    op.create_index(op.f("ix_dso_catalog_magnitude"), "dso_catalog", ["magnitude"], unique=False)
    op.create_index(op.f("ix_dso_catalog_object_type"), "dso_catalog", ["object_type"], unique=False)
    op.create_table(
        "image_source_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_name", sa.String(length=50), nullable=False),
        sa.Column("total_requests", sa.Integer(), nullable=False),
        sa.Column("successful_requests", sa.Integer(), nullable=False),
        sa.Column("failed_requests", sa.Integer(), nullable=False),
        sa.Column("avg_response_time_ms", sa.Float(), nullable=True),
        sa.Column("avg_quality_score", sa.Float(), nullable=True),
        sa.Column("priority_score", sa.Float(), nullable=True),
        sa.Column("last_used", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_name"),
    )
    op.create_index(op.f("ix_image_source_stats_id"), "image_source_stats", ["id"], unique=False)
    op.create_table(
        "observing_locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("elevation", sa.Float(), nullable=True),
        sa.Column("timezone", sa.String(), nullable=True),
        sa.Column("bortle_class", sa.Integer(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_observing_locations_id"), "observing_locations", ["id"], unique=False)
    op.create_table(
        "processing_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("file_type", sa.String(length=20), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("exposure_seconds", sa.Float(), nullable=True),
        sa.Column("filter_name", sa.String(length=10), nullable=True),
        sa.Column("temperature_celsius", sa.Float(), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("file_metadata", sa.JSON(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_processing_files_id"), "processing_files", ["id"], unique=False)
    op.create_table(
        "processing_pipelines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("pipeline_steps", sa.JSON(), nullable=False),
        sa.Column("is_preset", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_processing_pipelines_id"), "processing_pipelines", ["id"], unique=False)
    op.create_table(
        "saved_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("observing_date", sa.String(length=10), nullable=False),
        sa.Column("location_name", sa.String(length=100), nullable=False),
        sa.Column("plan_data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_saved_plans_id"), "saved_plans", ["id"], unique=False)
    op.create_table(
        "seestar_devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("control_host", sa.String(), nullable=True),
        sa.Column("control_port", sa.Integer(), nullable=True),
        sa.Column("is_control_enabled", sa.Boolean(), nullable=True),
        sa.Column("mount_path", sa.String(), nullable=True),
        sa.Column("is_mount_enabled", sa.Boolean(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_seestar_devices_id"), "seestar_devices", ["id"], unique=False)
    op.create_table(
        "star_catalog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("catalog_name", sa.String(length=10), nullable=False),
        sa.Column("catalog_number", sa.String(length=20), nullable=False),
        sa.Column("common_name", sa.String(length=100), nullable=True),
        sa.Column("bayer_designation", sa.String(length=20), nullable=True),
        sa.Column("flamsteed_number", sa.Integer(), nullable=True),
        sa.Column("ra_hours", sa.Float(), nullable=False),
        sa.Column("dec_degrees", sa.Float(), nullable=False),
        sa.Column("magnitude", sa.Float(), nullable=True),
        sa.Column("spectral_type", sa.String(length=20), nullable=True),
        sa.Column("distance_ly", sa.Float(), nullable=True),
        sa.Column("constellation", sa.String(length=3), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_star_catalog_catalog_name"), "star_catalog", ["catalog_name"], unique=False)
    op.create_index(op.f("ix_star_catalog_catalog_number"), "star_catalog", ["catalog_number"], unique=False)
    op.create_index(op.f("ix_star_catalog_common_name"), "star_catalog", ["common_name"], unique=False)
    op.create_index(op.f("ix_star_catalog_constellation"), "star_catalog", ["constellation"], unique=False)
    op.create_index(op.f("ix_star_catalog_dec_degrees"), "star_catalog", ["dec_degrees"], unique=False)
    op.create_index(op.f("ix_star_catalog_id"), "star_catalog", ["id"], unique=False)
    op.create_index(op.f("ix_star_catalog_magnitude"), "star_catalog", ["magnitude"], unique=False)
    op.create_table(
        "processing_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("pipeline_id", sa.Integer(), nullable=False),
        sa.Column("container_id", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("progress_percent", sa.Float(), nullable=True),
        sa.Column("current_step", sa.String(length=50), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("output_files", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("processing_log", sa.Text(), nullable=True),
        sa.Column("gpu_used", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["processing_files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["processing_pipelines.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_processing_jobs_id"), "processing_jobs", ["id"], unique=False)
    op.create_table(
        "telescope_executions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("execution_id", sa.String(length=50), nullable=False),
        sa.Column("celery_task_id", sa.String(length=255), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("total_targets", sa.Integer(), nullable=False),
        sa.Column("current_target_index", sa.Integer(), nullable=True),
        sa.Column("current_target_name", sa.String(length=100), nullable=True),
        sa.Column("current_phase", sa.String(length=50), nullable=True),
        sa.Column("targets_completed", sa.Integer(), nullable=True),
        sa.Column("targets_failed", sa.Integer(), nullable=True),
        sa.Column("progress_percent", sa.Float(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("elapsed_seconds", sa.Integer(), nullable=True),
        sa.Column("estimated_remaining_seconds", sa.Integer(), nullable=True),
        sa.Column("park_when_done", sa.Boolean(), nullable=True),
        sa.Column("telescope_host", sa.String(length=100), nullable=True),
        sa.Column("telescope_port", sa.Integer(), nullable=True),
        sa.Column("saved_plan_id", sa.Integer(), nullable=True),
        sa.Column("execution_result", sa.JSON(), nullable=True),
        sa.Column("error_log", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["saved_plan_id"],
            ["saved_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_telescope_executions_celery_task_id"), "telescope_executions", ["celery_task_id"], unique=True
    )
    op.create_index(op.f("ix_telescope_executions_execution_id"), "telescope_executions", ["execution_id"], unique=True)
    op.create_index(op.f("ix_telescope_executions_id"), "telescope_executions", ["id"], unique=False)
    op.create_index(op.f("ix_telescope_executions_state"), "telescope_executions", ["state"], unique=False)
    op.create_table(
        "telescope_execution_targets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("execution_id", sa.Integer(), nullable=False),
        sa.Column("target_index", sa.Integer(), nullable=False),
        sa.Column("target_name", sa.String(length=100), nullable=False),
        sa.Column("catalog_id", sa.String(length=50), nullable=True),
        sa.Column("ra_hours", sa.Float(), nullable=False),
        sa.Column("dec_degrees", sa.Float(), nullable=False),
        sa.Column("object_type", sa.String(length=50), nullable=True),
        sa.Column("magnitude", sa.Float(), nullable=True),
        sa.Column("scheduled_start_time", sa.DateTime(), nullable=False),
        sa.Column("scheduled_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("recommended_frames", sa.Integer(), nullable=True),
        sa.Column("recommended_exposure_seconds", sa.Integer(), nullable=True),
        sa.Column("started", sa.Boolean(), nullable=True),
        sa.Column("goto_completed", sa.Boolean(), nullable=True),
        sa.Column("focus_completed", sa.Boolean(), nullable=True),
        sa.Column("imaging_started", sa.Boolean(), nullable=True),
        sa.Column("imaging_completed", sa.Boolean(), nullable=True),
        sa.Column("actual_exposures", sa.Integer(), nullable=True),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("error_count", sa.Integer(), nullable=True),
        sa.Column("errors", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["telescope_executions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_telescope_execution_targets_execution_id"),
        "telescope_execution_targets",
        ["execution_id"],
        unique=False,
    )
    op.create_index(op.f("ix_telescope_execution_targets_id"), "telescope_execution_targets", ["id"], unique=False)
    op.create_table(
        "output_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("file_type", sa.String(length=20), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("catalog_id", sa.String(length=50), nullable=False),
        sa.Column("catalog_id_confidence", sa.Float(), nullable=True),
        sa.Column("execution_id", sa.Integer(), nullable=True),
        sa.Column("execution_target_id", sa.Integer(), nullable=True),
        sa.Column("exposure_seconds", sa.Integer(), nullable=True),
        sa.Column("filter_name", sa.String(length=20), nullable=True),
        sa.Column("temperature_celsius", sa.Float(), nullable=True),
        sa.Column("gain", sa.Integer(), nullable=True),
        sa.Column("fwhm", sa.Float(), nullable=True),
        sa.Column("star_count", sa.Integer(), nullable=True),
        sa.Column("observation_date", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["telescope_executions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["execution_target_id"],
            ["telescope_execution_targets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_output_files_catalog_id"), "output_files", ["catalog_id"], unique=False)
    op.create_index(op.f("ix_output_files_file_path"), "output_files", ["file_path"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_output_files_file_path"), table_name="output_files")
    op.drop_index(op.f("ix_output_files_catalog_id"), table_name="output_files")
    op.drop_table("output_files")
    op.drop_index(op.f("ix_telescope_execution_targets_id"), table_name="telescope_execution_targets")
    op.drop_index(op.f("ix_telescope_execution_targets_execution_id"), table_name="telescope_execution_targets")
    op.drop_table("telescope_execution_targets")
    op.drop_index(op.f("ix_telescope_executions_state"), table_name="telescope_executions")
    op.drop_index(op.f("ix_telescope_executions_id"), table_name="telescope_executions")
    op.drop_index(op.f("ix_telescope_executions_execution_id"), table_name="telescope_executions")
    op.drop_index(op.f("ix_telescope_executions_celery_task_id"), table_name="telescope_executions")
    op.drop_table("telescope_executions")
    op.drop_index(op.f("ix_processing_jobs_id"), table_name="processing_jobs")
    op.drop_table("processing_jobs")
    op.drop_index(op.f("ix_star_catalog_magnitude"), table_name="star_catalog")
    op.drop_index(op.f("ix_star_catalog_id"), table_name="star_catalog")
    op.drop_index(op.f("ix_star_catalog_dec_degrees"), table_name="star_catalog")
    op.drop_index(op.f("ix_star_catalog_constellation"), table_name="star_catalog")
    op.drop_index(op.f("ix_star_catalog_common_name"), table_name="star_catalog")
    op.drop_index(op.f("ix_star_catalog_catalog_number"), table_name="star_catalog")
    op.drop_index(op.f("ix_star_catalog_catalog_name"), table_name="star_catalog")
    op.drop_table("star_catalog")
    op.drop_index(op.f("ix_seestar_devices_id"), table_name="seestar_devices")
    op.drop_table("seestar_devices")
    op.drop_index(op.f("ix_saved_plans_id"), table_name="saved_plans")
    op.drop_table("saved_plans")
    op.drop_index(op.f("ix_processing_pipelines_id"), table_name="processing_pipelines")
    op.drop_table("processing_pipelines")
    op.drop_index(op.f("ix_processing_files_id"), table_name="processing_files")
    op.drop_table("processing_files")
    op.drop_index(op.f("ix_observing_locations_id"), table_name="observing_locations")
    op.drop_table("observing_locations")
    op.drop_index(op.f("ix_image_source_stats_id"), table_name="image_source_stats")
    op.drop_table("image_source_stats")
    op.drop_index(op.f("ix_dso_catalog_object_type"), table_name="dso_catalog")
    op.drop_index(op.f("ix_dso_catalog_magnitude"), table_name="dso_catalog")
    op.drop_index(op.f("ix_dso_catalog_id"), table_name="dso_catalog")
    op.drop_index(op.f("ix_dso_catalog_dec_degrees"), table_name="dso_catalog")
    op.drop_index(op.f("ix_dso_catalog_constellation"), table_name="dso_catalog")
    op.drop_index(op.f("ix_dso_catalog_common_name"), table_name="dso_catalog")
    op.drop_index(op.f("ix_dso_catalog_catalog_number"), table_name="dso_catalog")
    op.drop_index(op.f("ix_dso_catalog_catalog_name"), table_name="dso_catalog")
    op.drop_table("dso_catalog")
    op.drop_index(op.f("ix_constellation_names_id"), table_name="constellation_names")
    op.drop_table("constellation_names")
    op.drop_index(op.f("ix_comet_catalog_id"), table_name="comet_catalog")
    op.drop_table("comet_catalog")
    op.drop_index(op.f("ix_capture_history_catalog_id"), table_name="capture_history")
    op.drop_table("capture_history")
    op.drop_index(op.f("ix_asteroid_catalog_id"), table_name="asteroid_catalog")
    op.drop_table("asteroid_catalog")
    op.drop_index(op.f("ix_app_settings_key"), table_name="app_settings")
    op.drop_index(op.f("ix_app_settings_id"), table_name="app_settings")
    op.drop_index(op.f("ix_app_settings_category"), table_name="app_settings")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
