"""add_user_targets_table

Revision ID: 1eb59f1772f1
Revises: 00000002
Create Date: 2026-05-14 12:13:37.573264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb59f1772f1'
down_revision: Union[str, Sequence[str], None] = '00000002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ra_hours', sa.Float(), nullable=False),
    sa.Column('dec_degrees', sa.Float(), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('size_arcmin', sa.Float(), nullable=True),
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_targets_catalog_id'), 'user_targets', ['catalog_id'], unique=True)
    op.create_index(op.f('ix_user_targets_id'), 'user_targets', ['id'], unique=False)
    op.drop_index('ix_dso_catalog_type_mag_id', table_name='dso_catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_dso_catalog_type_mag_id', 'dso_catalog', ['object_type', 'magnitude', 'id'], unique=False)
    op.drop_index(op.f('ix_user_targets_id'), table_name='user_targets')
    op.drop_index(op.f('ix_user_targets_catalog_id'), table_name='user_targets')
    op.drop_table('user_targets')
    # ### end Alembic commands ###
