"""Add capture history and output files tables

Revision ID: c020a828cd8b
Revises: 2cc0b5ea228c
Create Date: 2025-12-30 07:18:15.560169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c020a828cd8b'
down_revision: Union[str, Sequence[str], None] = '2cc0b5ea228c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capture_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_id', sa.String(length=50), nullable=False),
    sa.Column('total_exposure_seconds', sa.Integer(), nullable=True),
    sa.Column('total_frames', sa.Integer(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=True),
    sa.Column('first_captured_at', sa.DateTime(), nullable=True),
    sa.Column('last_captured_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('suggested_status', sa.String(length=20), nullable=True),
    sa.Column('best_fwhm', sa.Float(), nullable=True),
    sa.Column('best_star_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capture_history_catalog_id'), 'capture_history', ['catalog_id'], unique=True)
    op.create_table('output_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('catalog_id', sa.String(length=50), nullable=False),
    sa.Column('catalog_id_confidence', sa.Float(), nullable=True),
    sa.Column('execution_id', sa.Integer(), nullable=True),
    sa.Column('execution_target_id', sa.Integer(), nullable=True),
    sa.Column('exposure_seconds', sa.Integer(), nullable=True),
    sa.Column('filter_name', sa.String(length=20), nullable=True),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('gain', sa.Integer(), nullable=True),
    sa.Column('fwhm', sa.Float(), nullable=True),
    sa.Column('star_count', sa.Integer(), nullable=True),
    sa.Column('observation_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['telescope_executions.id'], ),
    sa.ForeignKeyConstraint(['execution_target_id'], ['telescope_execution_targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_output_files_catalog_id'), 'output_files', ['catalog_id'], unique=False)
    op.create_index(op.f('ix_output_files_file_path'), 'output_files', ['file_path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_output_files_file_path'), table_name='output_files')
    op.drop_index(op.f('ix_output_files_catalog_id'), table_name='output_files')
    op.drop_table('output_files')
    op.drop_index(op.f('ix_capture_history_catalog_id'), table_name='capture_history')
    op.drop_table('capture_history')
    # ### end Alembic commands ###
